#sudo: true   #run build in virtualized machine with root access
language: node_js
node_js:
  - node   #use latest stable Node.js
cache:
  directories:
    - node_modules
jobs:
  include:
    - stage: "checks"
      name: "Type check"
      script: npm run check-types
    - stage: "checks"
      name: "Lint"
      script: npm run lint

